Add CI pipeline and MIT license
ebemunk/chess-tournament-grapher pull request #1
Opened 2020-04-29 12:37 UTC by ddugovic

2020-05-01 18:57 UTC, ebemunk approved these changes

2020-05-01 18:57 UTC, ebemunk commented on .gitignore
> -data/
you should leave these in, i think they were needed

2020-05-01 18:58 UTC, ebemunk commented
cool! thanks for doing this. i havent touched this repo in a long time but I don't think any of these changes can hurt. please add the 2 deleted items back into `.gitignore` though because I think they were needed for build

2020-05-01 18:59 UTC, ebemunk requested changes
add lines back to `.gitignore`

2020-05-01 19:26 UTC, ddugovic commented
Oops, sorry about that, and yes those are valuable so I don't accidentally upload local data.  Here you go!

2020-05-03 05:53 UTC, ebemunk approved these changes

2020-05-03 05:53 UTC, merged

2020-05-03 05:53 UTC, ebemunk commented
Thanks @ddugovic !